# Generated by Django 5.2.5 on 2025-08-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('person', models.CharField(choices=[('1', 'Person 1'), ('2', 'Person 2'), ('3', 'Person 3'), ('4', 'Person 4')], max_length=1)),
            ],
        ),
    ]
